### ISSUE TITLE
US5 - Réenregistrement d'un graphe

### ISSUE THREAD

**Issue by AntoineGouzy** [OskarMorel/GORAS_EditeurGrapheProbalistiques#11]
### User story
En tant qu'utilisateur
Je veux enregistrer un graphe ouvert à partir d’un fichier dans un fichier différent
Afin de créer une copie

**Comment by OskarMorel** [comment]
Reformule que je comprend rien

**Comment by rlbath** [comment]
C'est l'option Enregistrer-sous que j'évoque dans mon commentaire de la US1. Ok mais c'est mal formulé.
