### ISSUE TITLE
US13 - Afficher matrice de transition

### ISSUE THREAD

**Issue by gauthierjalbaud** [OskarMorel/GORAS_EditeurGrapheProbalistiques#20]
## User story
En tant que utilisateur
Je veux afficher la matrice de transition
Afin de connaître l'état initial du système

## Tests d'acceptation

Etant donné un utilisateur sur la page principale
Lorsqu'il clique sur le bouton "Matrice de transition"
Alors l'affiche

### Cas d'erreur
Etant donné un utilisateur sur la page principale mais que le graphe est vide
Alors ne peut pas cliquer sur le bouton "Matrice de transition"

Etant donné un utilisateur sur la page principale mais qu'il n'y a que des sommets mais pas d'arcs
Alors ne peut pas cliquer sur le bouton "Matrice de transition"

**Comment by rlbath** [comment]
Je pense que c'est OK mais à faire confirmer par M. Wherlé.

**Comment by LaurentWehrle** [comment]
L'affichage de la matrice de transition ne permet pas de connaître l'état initial du système.
L'état initial du système est déterminé par une loi de probabilité initiale.
La matrice de transition permet elle d'envisager l'évolution probable du système.

Dans les cas d'erreur, il faut ajouter a minima que les arcs doivent être valués avec des probas.
