### ISSUE TITLE
US3 - Choix de l'emplacement

### ISSUE THREAD

**Issue by AntoineGouzy** [OskarMorel/GORAS_EditeurGrapheProbalistiques#9]
###User story
En tant que utilisateur
Je veux choisir le dossier d'enregistrement
Afin de le retrouver plus facilement

### Tests d'acceptation
Etant donné un utilisateur sur le menu "Graphe"
Quand il clique sur "Enregistrer sous"
Alors le gestionnaire de fichiers s'ouvre afin d'enregistrer dans le dossier de mon choix

**Comment by rlbath** [comment]
Il faut envisager deux options d'enregistrement : enregistrer et enregistrer sous (voir mon commentaire de la US1).
